### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libffi.so.6: invalid ELF header

### ISSUE THREAD

**Issue by ssbarnea** [ssbarnea/netapp#2]
After starting **ONTAP Select 9.2 (ONTAPdeploy.raw)** using **virsh** with a line like:

```
virt-install --connect qemu:///system \
    --vcpus=2 --ram=4096 --name=netapp --os-type=linux \
    --controller=scsi,model=virtio-scsi \
    --network "type=bridge,source=br0,model=virtio,virtualport_type=openvswitch" \
    --disk path=ontap-select-9.2.qcow2,device=disk,bus=scsi,format=qcow2 \
    --console=pty --import --wait 0
```

Error:
```
virsh # console netapp
Connected to domain netapp
Escape character is ^]

That does not appear to be a valid hostname
Host name            : netapp
Use DHCP to set networking information? [n]: y


Selected host name    : netapp
Selected IP           : From DHCP
Selected net mask     : From DHCP
Selected gateway      : From DHCP
Selected primary DNS  : From DHCP
Selected secondary DNS: From DHCP
Search domains        : From DHCP
Calculated network    : From DHCP
Calculated broadcast  : From DHCP
Are these values correct? [y]: y


Applying network configuration. Please wait...


Continuing system startup. Please wait...

Debian GNU/Linux 8 netapp ttyS0

netapp login: admin
Password:
Linux netapp 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Traceback (most recent call last):
  File "/usr/bin/ONTAPdeploy", line 6, in <module>
    from shell import main
  File "/usr/local/lib/python2.7/sdotadmin_cli/shell.py", line 16, in <module>
    from cliff import app
  File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 14, in <module>
    from .utils import damerau_levenshtein, COST
  File "/usr/local/lib/python2.7/dist-packages/cliff/utils.py", line 14, in <module>
    import ctypes
  File "/usr/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: /usr/lib/x86_64-linux-gnu/libffi.so.6: invalid ELF header
```

`cat /proc/cpuinfo` on host:
```
processor	: 0 (..7)
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
stepping	: 3
microcode	: 0xba
cpu MHz		: 799.980
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bogomips	: 5424.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

**Comment by ssbarnea** [comment]
It seems that if I use the **raw** image directly instead of converting it to **qcow2** I do not endup with this error. 

I am not sure what is causing this but this is real deal because the raw image is **~42GB** and the qcow2 one is only **6GB.**. Transfering a 42GB image for each test execution could be real deal breaker.
